#!/usr/bin/env python3

import json
import locale
import sys
import reports
import emails
from operator import itemgetter

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  most_sales = {"car": "", "tally": 0}
  salesByYear = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # TODO: also handle max sales
    model = format_car(item["car"])
    total_sales = item["total_sales"]
    if total_sales > most_sales["tally"]:
      most_sales["car"] = model
      most_sales["tally"] = total_sales

    # TODO: also handle most popular car_year
    year = item["car"]["car_year"]
    if year not in salesByYear.keys():
      salesByYear[year] = 0
    salesByYear[year] += item["total_sales"]

  sorted_salesByYear = sorted(salesByYear.items(), key=lambda kv: (kv[1], kv[0]))
  (year, sale) = sorted_salesByYear[-1]

  summary = [
    "The {} generated the most revenue: ${}".format(format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(most_sales["car"], most_sales["tally"]),
    "The most popular year was {} with {} sales.".format(year, sale)
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    new_table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  table_data = cars_dict_to_table(data)
  # TODO: turn this into a PDF report
  reports.generate("/tmp/cars.pdf", "Sales summary for last month", "<br/>".join(summary), table_data)
  # TODO: send the PDF report as an email attachment
  sender = "automation@example.com"
  receiver = "<user>@example.com"
  subject = "Sales summary for last month"
  body = "\n".join(summary)
  attachment = "/tmp/cars.pdf"
  message = emails.generate(sender, receiver, subject, body, attachment)
  emails.send(message)

if __name__ == "__main__":
  main(sys.argv)
